#!/command/with-contenv sh
export NODE_ENV=production
export HOST=0.0.0.0
export PORT=8080
export DB_PATH=/app/data/db.sqlite
export PROMPTS_DIR=/app/prompts
export DEFAULT_PROMPTS_DIR=/app/default_prompts
cd /app
exec s6-setuidgid appuser node apps/api/dist/main.js
